# Generated by Django 3.1.6 on 2021-02-18 05:25

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('main_image', models.ImageField(upload_to='projects')),
                ('image1', models.ImageField(upload_to='projects')),
                ('image2', models.ImageField(upload_to='projects')),
                ('image3', models.ImageField(upload_to='projects')),
                ('image4', models.ImageField(upload_to='projects')),
                ('technologies', multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Flask', 'Flask'), ('JavaScript', 'JavaScript/Jquery'), ('HTML,CSS', 'HTML,CSS'), ('MySQL', 'MYSQL'), ('MongoDB', 'MongoDB'), ('PostgreSQL', 'PostgreSQL'), ('Java', 'Java Swing'), ('React', 'React')], max_length=75)),
            ],
        ),
    ]
